=== marcosmartinez25-debug/XSD-RegEx/Validar XML-XSD/empleados.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="EdadType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="120"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="empresa">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="empleado" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="apellido" type="xs:string"/>
              <xs:element name="edad" type="EdadType"/>
              <xs:element name="departamento" type="xs:string"/>
              <xs:element name="cargo" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== marcosmartinez25-debug/XSD-RegEx/Validar XML-XSD/empleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="empleados.xsd">

  <empleado id="1">
    <nombre>Ana</nombre>
    <apellido>García</apellido>
    <edad>30</edad>
    <departamento>Ventas</departamento>
    <cargo>Ejecutivo de ventas</cargo>
  </empleado>

  <empleado id="2">
    <nombre>Luis</nombre>
    <apellido>Rodríguez</apellido>
    <edad>45</edad>
    <departamento>Finanzas</departamento>
    <cargo>Analista financiero</cargo>
  </empleado>

  <empleado id="3">
    <nombre>María</nombre>
    <apellido>López</apellido>
    <edad>28</edad>
    <departamento>Marketing</departamento>
    <cargo>Especialista en redes sociales</cargo>
  </empleado>

  <empleado id="4">
    <nombre>Marcos</nombre>
    <apellido>Martinez</apellido>
    <edad>19</edad>
    <departamento>DAW</departamento>
    <cargo>Programador junior</cargo>
  </empleado>

  <empleado id="5">
    <nombre>Daniel</nombre>
    <apellido>Ortiz</apellido>
    <edad>18</edad>
    <departamento>DAW</departamento>
    <cargo>Programador junior</cargo>
  </empleado>

  <empleado id="6">
    <nombre>Jose Luis</nombre>
    <apellido>Contreras</apellido>
    <edad>20</edad>
    <departamento>DAW</departamento>
    <cargo>Programador junior</cargo>
  </empleado>

  <empleado id="7">
    <nombre>Adrian</nombre>
    <apellido>Cabezas</apellido>
    <edad>26</edad>
    <departamento>DAW</departamento>
    <cargo>Programador</cargo>
  </empleado>

  <empleado id="8">
    <nombre>Jose Maria</nombre>
    <apellido>Salas</apellido>
    <edad>18</edad>
    <departamento>DAW</departamento>
    <cargo>Programador junior</cargo>
  </empleado>

  <empleado id="9">
    <nombre>Alberto</nombre>
    <apellido>Rueda</apellido>
    <edad>21</edad>
    <departamento>DAW</departamento>
    <cargo>Desarrollador web</cargo>
  </empleado>

  <empleado id="E10">
    <nombre>Daniela</nombre>
    <apellido>Martinez</apellido>
    <edad>22</edad>
    <departamento>Educacion Infantil</departamento>
    <cargo>Educadora</cargo>
  </empleado>

  <empleado id="E11">
    <nombre>Pablo</nombre>
    <apellido>Delgado</apellido>
    <edad>18</edad>
    <departamento>DAW</departamento>
    <cargo>Programador junior</cargo>
  </empleado>

  <empleado id="E12">
    <nombre>David</nombre>
    <apellido>Delgado</apellido>
    <edad>18</edad>
    <departamento>DAW</departamento>
    <cargo>Programador junior</cargo>
  </empleado>

  <empleado id="E13">
    <nombre>Manuel</nombre>
    <apellido>Parrilla</apellido>
    <edad>30</edad>
    <departamento>DAW</departamento>
    <cargo>Programador senior</cargo>
  </empleado>
</empresa>
